### ISSUE TITLE
Why addPushManifest in bundled presets?

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer-project-config#39]
https://github.com/Polymer/polymer-project-config/blob/22edadb236173a1151beb92f0a9eafda6df84a2f/src/builds.ts#L168-L177

https://github.com/Polymer/polymer-project-config/blob/22edadb236173a1151beb92f0a9eafda6df84a2f/src/builds.ts#L156-L164

This should be `false`, right?

***

I will create the PR because the change is very fast.

**Comment by aomarks** [comment]
@usergenic Thoughts? Do we ever want to push non-entrypoint fragment bundles?

**Comment by usergenic** [comment]
I think pushing non-entrypoint bundles, like shell for example, is feature-gated on etag/cache/dictionary/whatever its going to be implemented as.  If the primary cost of pushed assets could be absorbed by browser cache, I think we would probably push them, but since I don't think they do, my instinct is we wouldn't want to do that yet, since it would result in a lot of potentially heavy redundant payload.

**Comment by aomarks** [comment]
@usergenic Just to double check, you're OK with the change @abdonrd proposed in https://github.com/Polymer/polymer-project-config/pull/40?

**Comment by usergenic** [comment]
Yeah I think that makes sense.  Insofar as addPushManifest is essentially only providing push hints for html imports right now this makes sense.  If it becomes more nuanced than that, addPushManifest might later be adapted to take an object with options for other controls, like if we decide it makes sense to identify other assets to include in the push manifest etc.

**Comment by usergenic** [comment]
...i.e. images, external scripts or css etc.
